import Head from 'next/head'
import Layout from '../components/Layout/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-xl font-medium text-black">Hello, world !</h1>
    </Layout>
  )
}
